spring:
  application:
    name: service-discovery-server

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    hostname: service-discovery
    prefer-ip-address: false
